---
title: "Introduction to tblCrud (draft)"
author: "Andrea Melloncelli"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Purposes and design

## Precondition on tables

Tables we use will be characterise by one column which will be the *primary_id* or the *rowname* of the column. The type of this variable is `string`, `factor` or `integer`.

The second kind of id is the incremental integer number of the database: the *incremental_id*. This is necessary only in case more than one user access to the database and if the user wants to change a primary_id without lose the connection with the database.

NB: the two id can be the same. At the moment they are confused in the code.

# Usage

## Typical usage

1. Create an empty table in the database with the schema of a data frame.
2. Append data to it.
3. Modify old data and append new data and sincronize the data on db.

## Specific usage

# Compatibility

## Databases

At the moment it is tested only with SQLite.
